### ISSUE TITLE
Wpis Jaszczur na listę bez UB

### ISSUE THREAD

**Issue by Herato** [MrucznikRolePlay/Forum#6]
https://mrucznik-rp.pl/topic/76814-oban-jaszczur/

Brak chęci poprawy, po otrzymaniu 6 warna od MG Klemuś (a co za tym idzie blokade konta) napisał bardzo wulgarną apelację obrażającą tego moderatora. Teraz otrzymał bana.

**Comment by ReQuien** [comment]
Dodatkowo warto dodać że mieszka na bemowie a to nie jest ciekawa okolica.
Co do samego wpisu, warto dodać że użytkownik na własne życzenie dostał blokadę konta za offtop, następnie nie raczył niczego wyjaśniać, wolał rzucać mięsem na prawo i lewo rzucając różnymi obrazami w kierunku moderatora nadającego mu karę za offtop a jednoczenie blokadę konta.
